/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp firewalld-config-ipset.xml -p firewalld_config_ipset_interface -i generictypes.h -V
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd and other contributors.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef FIREWALLD_CONFIG_IPSET_INTERFACE_H
#define FIREWALLD_CONFIG_IPSET_INTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "generictypes.h"

/*
 * Proxy class for interface org.fedoraproject.FirewallD1.config.ipset
 */
class OrgFedoraprojectFirewallD1ConfigIpsetInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.fedoraproject.FirewallD1.config.ipset"; }

public:
    OrgFedoraprojectFirewallD1ConfigIpsetInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgFedoraprojectFirewallD1ConfigIpsetInterface();

    Q_PROPERTY(bool builtin READ builtin)
    inline bool builtin() const
    { return qvariant_cast< bool >(property("builtin")); }

    // Renamed from default to isDefeault, as default is a keyword and not allowed
    Q_PROPERTY(bool isDefault READ isDefault)
    inline bool isDefault() const
    { return qvariant_cast< bool >(property("default")); }

    Q_PROPERTY(QString filename READ filename)
    inline QString filename() const
    { return qvariant_cast< QString >(property("filename")); }

    Q_PROPERTY(QString name READ name)
    inline QString name() const
    { return qvariant_cast< QString >(property("name")); }

    Q_PROPERTY(QString path READ path)
    inline QString path() const
    { return qvariant_cast< QString >(property("path")); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> addEntry(const QString &entry)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(entry);
        return asyncCallWithArgumentList(QStringLiteral("addEntry"), argumentList);
    }

    inline QDBusPendingReply<> addOption(const QString &key, const QString &value)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(key) << QVariant::fromValue(value);
        return asyncCallWithArgumentList(QStringLiteral("addOption"), argumentList);
    }

    inline QDBusPendingReply<QString> getDescription()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("getDescription"), argumentList);
    }

    inline QDBusPendingReply<QStringList> getEntries()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("getEntries"), argumentList);
    }

    inline QDBusPendingReply<FWStringMap> getOptions()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("getOptions"), argumentList);
    }

    inline QDBusPendingReply<FWIPSetSettings> getSettings()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("getSettings"), argumentList);
    }

    inline QDBusPendingReply<QString> getShort()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("getShort"), argumentList);
    }

    inline QDBusPendingReply<QString> getType()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("getType"), argumentList);
    }

    inline QDBusPendingReply<QString> getVersion()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("getVersion"), argumentList);
    }

    inline QDBusPendingReply<> loadDefaults()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("loadDefaults"), argumentList);
    }

    inline QDBusPendingReply<bool> queryEntry(const QString &entry)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(entry);
        return asyncCallWithArgumentList(QStringLiteral("queryEntry"), argumentList);
    }

    inline QDBusPendingReply<bool> queryOption(const QString &key, const QString &value)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(key) << QVariant::fromValue(value);
        return asyncCallWithArgumentList(QStringLiteral("queryOption"), argumentList);
    }

    inline QDBusPendingReply<> remove()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("remove"), argumentList);
    }

    inline QDBusPendingReply<> removeEntry(const QString &entry)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(entry);
        return asyncCallWithArgumentList(QStringLiteral("removeEntry"), argumentList);
    }

    inline QDBusPendingReply<> removeOption(const QString &key)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(key);
        return asyncCallWithArgumentList(QStringLiteral("removeOption"), argumentList);
    }

    inline QDBusPendingReply<> rename(const QString &name)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(name);
        return asyncCallWithArgumentList(QStringLiteral("rename"), argumentList);
    }

    inline QDBusPendingReply<> setDescription(const QString &description)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(description);
        return asyncCallWithArgumentList(QStringLiteral("setDescription"), argumentList);
    }

    inline QDBusPendingReply<> setEntries(const QStringList &entries)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(entries);
        return asyncCallWithArgumentList(QStringLiteral("setEntries"), argumentList);
    }

    inline QDBusPendingReply<> setOptions(FWStringMap options)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(options);
        return asyncCallWithArgumentList(QStringLiteral("setOptions"), argumentList);
    }

    // rename argument short to shortName as short is a reserved keyword
    inline QDBusPendingReply<> setShort(const QString &shortName)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(shortName);
        return asyncCallWithArgumentList(QStringLiteral("setShort"), argumentList);
    }

    inline QDBusPendingReply<> setType(const QString &ipset_type)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(ipset_type);
        return asyncCallWithArgumentList(QStringLiteral("setType"), argumentList);
    }

    inline QDBusPendingReply<> setVersion(const QString &version)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(version);
        return asyncCallWithArgumentList(QStringLiteral("setVersion"), argumentList);
    }

    inline QDBusPendingReply<> update(FWIPSetSettings settings)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(settings);
        return asyncCallWithArgumentList(QStringLiteral("update"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void Removed(const QString &name);
    void Renamed(const QString &name);
    void Updated(const QString &name);
};

namespace org {
  namespace fedoraproject {
    namespace FirewallD1 {
      namespace config {
        using ipset = ::OrgFedoraprojectFirewallD1ConfigIpsetInterface;
      }
    }
  }
}
#endif
