/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp firewalld-config.xml -p firewalld_config_interface -i generictypes.h -V
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd and other contributors.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "firewalld_config_interface.h"

/*
 * Implementation of interface class OrgFedoraprojectFirewallD1ConfigInterface
 */

OrgFedoraprojectFirewallD1ConfigInterface::OrgFedoraprojectFirewallD1ConfigInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFedoraprojectFirewallD1ConfigInterface::~OrgFedoraprojectFirewallD1ConfigInterface()
{
}

/*
 * Implementation of interface class OrgFedoraprojectFirewallD1ConfigPoliciesInterface
 */

OrgFedoraprojectFirewallD1ConfigPoliciesInterface::OrgFedoraprojectFirewallD1ConfigPoliciesInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFedoraprojectFirewallD1ConfigPoliciesInterface::~OrgFedoraprojectFirewallD1ConfigPoliciesInterface()
{
}

