/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp firewalld.xml -p firewalld_interface -i generictypes.h -V
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd and other contributors.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "firewalld_interface.h"

/*
 * Implementation of interface class OrgFedoraprojectFirewallD1Interface
 */

OrgFedoraprojectFirewallD1Interface::OrgFedoraprojectFirewallD1Interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFedoraprojectFirewallD1Interface::~OrgFedoraprojectFirewallD1Interface()
{
}

/*
 * Implementation of interface class OrgFedoraprojectFirewallD1IpsetInterface
 */

OrgFedoraprojectFirewallD1IpsetInterface::OrgFedoraprojectFirewallD1IpsetInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFedoraprojectFirewallD1IpsetInterface::~OrgFedoraprojectFirewallD1IpsetInterface()
{
}

/*
 * Implementation of interface class OrgFedoraprojectFirewallD1PoliciesInterface
 */

OrgFedoraprojectFirewallD1PoliciesInterface::OrgFedoraprojectFirewallD1PoliciesInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFedoraprojectFirewallD1PoliciesInterface::~OrgFedoraprojectFirewallD1PoliciesInterface()
{
}

/*
 * Implementation of interface class OrgFedoraprojectFirewallD1PolicyInterface
 */

OrgFedoraprojectFirewallD1PolicyInterface::OrgFedoraprojectFirewallD1PolicyInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFedoraprojectFirewallD1PolicyInterface::~OrgFedoraprojectFirewallD1PolicyInterface()
{
}

/*
 * Implementation of interface class OrgFedoraprojectFirewallD1ZoneInterface
 */

OrgFedoraprojectFirewallD1ZoneInterface::OrgFedoraprojectFirewallD1ZoneInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFedoraprojectFirewallD1ZoneInterface::~OrgFedoraprojectFirewallD1ZoneInterface()
{
}

