/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp firewalld-config-ipset.xml -p firewalld_config_ipset_interface -i generictypes.h -V
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd and other contributors.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "firewalld_config_ipset_interface.h"

/*
 * Implementation of interface class OrgFedoraprojectFirewallD1ConfigIpsetInterface
 */

OrgFedoraprojectFirewallD1ConfigIpsetInterface::OrgFedoraprojectFirewallD1ConfigIpsetInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFedoraprojectFirewallD1ConfigIpsetInterface::~OrgFedoraprojectFirewallD1ConfigIpsetInterface()
{
}

